export const ERROR_CODE = {
	UNAUTHORIZED: "UNAUTHORIZED",
	FORBIDDEN: "FORBIDDEN",
	NOT_FOUND: "NOT_FOUND",
	VALIDATION_ERROR: "VALIDATION_ERROR",
	BAD_REQUEST: "BAD_REQUEST",
	CONFLICT: "CONFLICT",
	INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode =
	(typeof ERROR_CODE)[keyof typeof ERROR_CODE];
